// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleServiceCenter;

#nullable disable

namespace VehicleServiceCenter.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260812211906_ReplaceAllSeedData")]
    partial class ReplaceAllSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleServiceCenter.Models.AppointmentModel", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("MechanicProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("MechanicProfileId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 1,
                            CreatedAt = new DateTime(2026, 7, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 1,
                            MechanicProfileId = 1,
                            Notes = "Scheduled oil-change maintenance",
                            ServiceTypeId = 1,
                            Status = "Completed",
                            VehicleId = 1
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDate = new DateTime(2026, 8, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 2,
                            CreatedAt = new DateTime(2026, 8, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 1,
                            MechanicProfileId = 2,
                            Notes = "Air conditioner is not cooling properly",
                            ServiceTypeId = 5,
                            Status = "Confirmed",
                            VehicleId = 2
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDate = new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 1,
                            CreatedAt = new DateTime(2026, 8, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 2,
                            MechanicProfileId = 1,
                            Notes = "Noise while braking",
                            ServiceTypeId = 2,
                            Status = "In Progress",
                            VehicleId = 3
                        },
                        new
                        {
                            AppointmentId = 7,
                            AppointmentDate = new DateTime(2026, 8, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 2,
                            CreatedAt = new DateTime(2026, 8, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 3,
                            MechanicProfileId = 2,
                            Notes = "Check-engine warning light is on",
                            ServiceTypeId = 3,
                            Status = "Confirmed",
                            VehicleId = 4
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentDate = new DateTime(2026, 8, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 1,
                            CreatedAt = new DateTime(2026, 8, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 2,
                            Notes = "Battery is slow during startup",
                            ServiceTypeId = 4,
                            Status = "Pending",
                            VehicleId = 3
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppointmentDate = new DateTime(2026, 8, 12, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 2,
                            CreatedAt = new DateTime(2026, 8, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 3,
                            MechanicProfileId = 2,
                            Notes = "Customer cancelled the appointment",
                            ServiceTypeId = 1,
                            Status = "Cancelled",
                            VehicleId = 4
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.BranchModel", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Address = "Al Khuwair, Muscat, Oman",
                            BranchName = "Muscat Main Branch",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "muscat@vehicleservice.com",
                            IsActive = true,
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            PhoneNumber = "24000001"
                        },
                        new
                        {
                            BranchId = 2,
                            Address = "Al Hail, Seeb, Oman",
                            BranchName = "Seeb Branch",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "seeb@vehicleservice.com",
                            IsActive = true,
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            PhoneNumber = "24000002"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.CustomerProfileModel", b =>
                {
                    b.Property<int>("CustomerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");

                    b.HasData(
                        new
                        {
                            CustomerProfileId = 1,
                            Address = "Bawshar, Muscat, Oman",
                            CreatedAt = new DateTime(2026, 1, 2, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1995, 4, 12),
                            UserId = 3
                        },
                        new
                        {
                            CustomerProfileId = 2,
                            Address = "Al Amerat, Muscat, Oman",
                            CreatedAt = new DateTime(2026, 1, 3, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1990, 9, 21),
                            UserId = 4
                        },
                        new
                        {
                            CustomerProfileId = 3,
                            Address = "Al Hail, Seeb, Oman",
                            CreatedAt = new DateTime(2026, 1, 4, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1998, 2, 7),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.InvoiceModel", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ServiceOrderId")
                        .IsUnique();

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            DiscountAmount = 0m,
                            DueDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0001",
                            IssueDate = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Paid in full",
                            ServiceOrderId = 1,
                            Status = "Paid",
                            Subtotal = 36m,
                            TaxAmount = 0m,
                            TotalAmount = 36m
                        },
                        new
                        {
                            InvoiceId = 2,
                            DiscountAmount = 0m,
                            DueDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0002",
                            IssueDate = new DateTime(2026, 8, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Partial payment received",
                            ServiceOrderId = 2,
                            Status = "Unpaid",
                            Subtotal = 74m,
                            TaxAmount = 0m,
                            TotalAmount = 74m
                        },
                        new
                        {
                            InvoiceId = 3,
                            DiscountAmount = 0m,
                            DueDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0003",
                            IssueDate = new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Payment is due after service completion",
                            ServiceOrderId = 3,
                            Status = "Unpaid",
                            Subtotal = 45m,
                            TaxAmount = 0m,
                            TotalAmount = 45m
                        },
                        new
                        {
                            InvoiceId = 4,
                            DiscountAmount = 0m,
                            DueDate = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0004",
                            IssueDate = new DateTime(2026, 8, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Pending payment recorded",
                            ServiceOrderId = 4,
                            Status = "Unpaid",
                            Subtotal = 78m,
                            TaxAmount = 0m,
                            TotalAmount = 78m
                        },
                        new
                        {
                            InvoiceId = 5,
                            DiscountAmount = 0m,
                            DueDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0005",
                            IssueDate = new DateTime(2026, 8, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Paid in full",
                            ServiceOrderId = 5,
                            Status = "Paid",
                            Subtotal = 105m,
                            TaxAmount = 0m,
                            TotalAmount = 105m
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.MechanicProfileModel", b =>
                {
                    b.Property<int>("MechanicProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicProfileId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MechanicProfileId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MechanicProfiles");

                    b.HasData(
                        new
                        {
                            MechanicProfileId = 1,
                            BranchId = 1,
                            ExperienceYears = 8,
                            HireDate = new DateOnly(2021, 3, 15),
                            IsAvailable = true,
                            Specialization = "Engine and Brake Systems",
                            UserId = 6
                        },
                        new
                        {
                            MechanicProfileId = 2,
                            BranchId = 2,
                            ExperienceYears = 6,
                            HireDate = new DateOnly(2022, 6, 1),
                            IsAvailable = true,
                            Specialization = "Electrical and Air Conditioning",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.PaymentModel", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasFilter("[TransactionReference] IS NOT NULL");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 36m,
                            InvoiceId = 1,
                            Notes = "Full card payment",
                            PaymentDate = new DateTime(2026, 8, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            Status = "Completed",
                            TransactionReference = "PAY-2026-0001"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 30m,
                            InvoiceId = 2,
                            Notes = "Partial cash payment",
                            PaymentDate = new DateTime(2026, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            Status = "Completed",
                            TransactionReference = "PAY-2026-0002"
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 105m,
                            InvoiceId = 5,
                            Notes = "Full card payment",
                            PaymentDate = new DateTime(2026, 8, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            Status = "Completed",
                            TransactionReference = "PAY-2026-0003"
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 20m,
                            InvoiceId = 4,
                            Notes = "Online payment awaiting confirmation",
                            PaymentDate = new DateTime(2026, 8, 20, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Online",
                            Status = "Pending",
                            TransactionReference = "PAY-2026-0004"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderItemModel", b =>
                {
                    b.Property<int>("ServiceOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceOrderItemId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("LaborHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SparePartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ServiceOrderItemId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("SparePartId");

                    b.ToTable("ServiceOrderItems");

                    b.HasData(
                        new
                        {
                            ServiceOrderItemId = 1,
                            Description = "Oil-change labor",
                            ItemType = "Service",
                            LaborHours = 0.75m,
                            Quantity = 1,
                            ServiceOrderId = 1,
                            ServiceTypeId = 1,
                            Subtotal = 25m,
                            UnitPrice = 25m
                        },
                        new
                        {
                            ServiceOrderItemId = 2,
                            Description = "Oil-filter replacement",
                            ItemType = "SparePart",
                            Quantity = 1,
                            ServiceOrderId = 1,
                            SparePartId = 1,
                            Subtotal = 11m,
                            UnitPrice = 11m
                        },
                        new
                        {
                            ServiceOrderItemId = 3,
                            Description = "Brake inspection labor",
                            ItemType = "Service",
                            LaborHours = 1m,
                            Quantity = 1,
                            ServiceOrderId = 2,
                            ServiceTypeId = 2,
                            Subtotal = 30m,
                            UnitPrice = 30m
                        },
                        new
                        {
                            ServiceOrderItemId = 4,
                            Description = "Front brake-pad set",
                            ItemType = "SparePart",
                            Quantity = 1,
                            ServiceOrderId = 2,
                            SparePartId = 2,
                            Subtotal = 44m,
                            UnitPrice = 44m
                        },
                        new
                        {
                            ServiceOrderItemId = 5,
                            Description = "Engine diagnostic scan",
                            ItemType = "Service",
                            LaborHours = 1m,
                            Quantity = 1,
                            ServiceOrderId = 3,
                            ServiceTypeId = 3,
                            Subtotal = 45m,
                            UnitPrice = 45m
                        },
                        new
                        {
                            ServiceOrderItemId = 6,
                            Description = "Air-conditioning inspection and service",
                            ItemType = "Service",
                            LaborHours = 1.5m,
                            Quantity = 1,
                            ServiceOrderId = 4,
                            ServiceTypeId = 5,
                            Subtotal = 60m,
                            UnitPrice = 60m
                        },
                        new
                        {
                            ServiceOrderItemId = 7,
                            Description = "Cabin air-filter replacement",
                            ItemType = "SparePart",
                            Quantity = 1,
                            ServiceOrderId = 4,
                            SparePartId = 4,
                            Subtotal = 18m,
                            UnitPrice = 18m
                        },
                        new
                        {
                            ServiceOrderItemId = 8,
                            Description = "Battery testing and installation",
                            ItemType = "Service",
                            LaborHours = 0.5m,
                            Quantity = 1,
                            ServiceOrderId = 5,
                            ServiceTypeId = 4,
                            Subtotal = 20m,
                            UnitPrice = 20m
                        },
                        new
                        {
                            ServiceOrderItemId = 9,
                            Description = "12-volt replacement battery",
                            ItemType = "SparePart",
                            Quantity = 1,
                            ServiceOrderId = 5,
                            SparePartId = 3,
                            Subtotal = 85m,
                            UnitPrice = 85m
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderModel", b =>
                {
                    b.Property<int>("ServiceOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceOrderId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerComplaint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MechanicProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ServiceOrderId");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("MechanicProfileId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceOrders");

                    b.HasData(
                        new
                        {
                            ServiceOrderId = 1,
                            AppointmentId = 1,
                            BranchId = 1,
                            CompletionDate = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Routine oil-change service",
                            CustomerProfileId = 1,
                            Diagnosis = "Oil and oil filter were due for replacement",
                            MechanicProfileId = 1,
                            OrderDate = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 36m,
                            VehicleId = 1
                        },
                        new
                        {
                            ServiceOrderId = 2,
                            AppointmentId = 3,
                            BranchId = 1,
                            CreatedAt = new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Noise and vibration while braking",
                            CustomerProfileId = 2,
                            Diagnosis = "Front brake pads require replacement",
                            MechanicProfileId = 1,
                            OrderDate = new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TotalAmount = 74m,
                            VehicleId = 3
                        },
                        new
                        {
                            ServiceOrderId = 3,
                            AppointmentId = 7,
                            BranchId = 2,
                            CreatedAt = new DateTime(2026, 8, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Check-engine warning light is on",
                            CustomerProfileId = 3,
                            Diagnosis = "Diagnostic scan is approved and waiting to begin",
                            MechanicProfileId = 2,
                            OrderDate = new DateTime(2026, 8, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            TotalAmount = 45m,
                            VehicleId = 4
                        },
                        new
                        {
                            ServiceOrderId = 4,
                            AppointmentId = 2,
                            BranchId = 2,
                            CreatedAt = new DateTime(2026, 8, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Air conditioner is not cooling properly",
                            CustomerProfileId = 1,
                            Diagnosis = "Air-conditioning inspection is pending",
                            MechanicProfileId = 2,
                            OrderDate = new DateTime(2026, 8, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalAmount = 78m,
                            VehicleId = 2
                        },
                        new
                        {
                            ServiceOrderId = 5,
                            BranchId = 1,
                            CompletionDate = new DateTime(2026, 8, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 8, 12, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Vehicle would not start",
                            CustomerProfileId = 2,
                            Diagnosis = "Battery failed its load test and was replaced",
                            MechanicProfileId = 1,
                            OrderDate = new DateTime(2026, 8, 12, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 105m,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceTypeModel", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            ServiceTypeId = 1,
                            BasePrice = 25m,
                            Description = "Engine oil and oil-filter replacement",
                            EstimatedDurationMinutes = 45,
                            IsActive = true,
                            Name = "Oil Change"
                        },
                        new
                        {
                            ServiceTypeId = 2,
                            BasePrice = 30m,
                            Description = "Complete brake-system inspection",
                            EstimatedDurationMinutes = 60,
                            IsActive = true,
                            Name = "Brake Inspection"
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            BasePrice = 45m,
                            Description = "Computerized engine diagnostic service",
                            EstimatedDurationMinutes = 60,
                            IsActive = true,
                            Name = "Engine Diagnostic"
                        },
                        new
                        {
                            ServiceTypeId = 4,
                            BasePrice = 20m,
                            Description = "Battery testing and replacement service",
                            EstimatedDurationMinutes = 30,
                            IsActive = true,
                            Name = "Battery Replacement"
                        },
                        new
                        {
                            ServiceTypeId = 5,
                            BasePrice = 60m,
                            Description = "Air-conditioning inspection and maintenance",
                            EstimatedDurationMinutes = 90,
                            IsActive = true,
                            Name = "Air Conditioning Service"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.SparePartModel", b =>
                {
                    b.Property<int>("SparePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SparePartId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SparePartId");

                    b.HasIndex("BranchId");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("SpareParts");

                    b.HasData(
                        new
                        {
                            SparePartId = 1,
                            BranchId = 1,
                            Description = "Standard engine oil filter",
                            IsAvailable = true,
                            PartName = "Oil Filter",
                            PartNumber = "OF-001",
                            ReorderLevel = 10,
                            StockQuantity = 45,
                            UnitPrice = 11m
                        },
                        new
                        {
                            SparePartId = 2,
                            BranchId = 1,
                            Description = "Front axle ceramic brake-pad set",
                            IsAvailable = true,
                            PartName = "Front Brake Pads",
                            PartNumber = "BP-001",
                            ReorderLevel = 5,
                            StockQuantity = 18,
                            UnitPrice = 44m
                        },
                        new
                        {
                            SparePartId = 3,
                            BranchId = 1,
                            Description = "12-volt maintenance-free vehicle battery",
                            IsAvailable = true,
                            PartName = "Car Battery",
                            PartNumber = "BAT-001",
                            ReorderLevel = 3,
                            StockQuantity = 12,
                            UnitPrice = 85m
                        },
                        new
                        {
                            SparePartId = 4,
                            BranchId = 2,
                            Description = "Cabin air filter for climate-control systems",
                            IsAvailable = true,
                            PartName = "Cabin Air Filter",
                            PartNumber = "CAF-001",
                            ReorderLevel = 6,
                            StockQuantity = 25,
                            UnitPrice = 18m
                        },
                        new
                        {
                            SparePartId = 5,
                            BranchId = 2,
                            Description = "Standard engine intake air filter",
                            IsAvailable = true,
                            PartName = "Engine Air Filter",
                            PartNumber = "EAF-001",
                            ReorderLevel = 7,
                            StockQuantity = 30,
                            UnitPrice = 15m
                        },
                        new
                        {
                            SparePartId = 6,
                            BranchId = 2,
                            Description = "Four-piece iridium spark-plug set",
                            IsAvailable = true,
                            PartName = "Spark Plug Set",
                            PartNumber = "SP-001",
                            ReorderLevel = 5,
                            StockQuantity = 4,
                            UnitPrice = 32m
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            IsActive = true,
                            Password = "$2a$11$GiQ5o4CPh1sr1GQQVxyv2O51hdE2lXCVHbfQJRdR667WwFe0EYR6m",
                            PhoneNumber = "90000001",
                            Role = "Admin",
                            UserName = "Admin User"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer1@gmail.com",
                            IsActive = true,
                            Password = "$2a$11$WHsBifzPW/23FBBmsDb/pOWH5CFLr7xgXt85f7Y7Q36m51nHJBamC",
                            PhoneNumber = "91110001",
                            Role = "Customer",
                            UserName = "Sara Al Balushi"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 1, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer2@gmail.com",
                            IsActive = true,
                            Password = "$2a$11$2W08xdjKhmOrb.XzkPvUwuYEPStJe0V.HixHDfa.A04RcdoqlYC1i",
                            PhoneNumber = "92220002",
                            Role = "Customer",
                            UserName = "Omar Al Harthi"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 1, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer3@gmail.com",
                            IsActive = true,
                            Password = "$2a$11$PR.SYUMNka84Z8vjRcx89.dWEZieqCKueqHAw1ypZrRsXxD8Z2UAS",
                            PhoneNumber = "93330003",
                            Role = "Customer",
                            UserName = "Lina Al Lawati"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mechanic1@gmail.com",
                            IsActive = true,
                            Password = "$2a$11$vekQUchkuBwnXV1BdoGv3u/2QaQRQhGd.RrDZyyjvM.my4x9S5O.S",
                            PhoneNumber = "94440004",
                            Role = "Mechanic",
                            UserName = "Ahmed Al Rashdi"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mechanic2@gmail.com",
                            IsActive = true,
                            Password = "$2a$11$/YWclfj9mFqcGGPnoo0p0.X0zZ0jSOgj7nhrrngllAdcSg4Tl1n.m",
                            PhoneNumber = "95550005",
                            Role = "Mechanic",
                            UserName = "Khalid Al Siyabi"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.VehicleModel", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Mileage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VIN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.HasIndex("VIN")
                        .IsUnique()
                        .HasFilter("[VIN] IS NOT NULL");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Color = "White",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 1,
                            Make = "Toyota",
                            Mileage = 45000m,
                            Model = "Camry",
                            PlateNumber = "OM-10001",
                            VIN = "OMVIN2026000000001",
                            Year = 2022
                        },
                        new
                        {
                            VehicleId = 2,
                            Color = "Black",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 1,
                            Make = "Lexus",
                            Mileage = 28500m,
                            Model = "NX 350",
                            PlateNumber = "OM-10002",
                            VIN = "OMVIN2026000000002",
                            Year = 2023
                        },
                        new
                        {
                            VehicleId = 3,
                            Color = "Silver",
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 2,
                            Make = "Nissan",
                            Mileage = 62000m,
                            Model = "Altima",
                            PlateNumber = "OM-20001",
                            VIN = "OMVIN2026000000003",
                            Year = 2021
                        },
                        new
                        {
                            VehicleId = 4,
                            Color = "Blue",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 3,
                            Make = "Honda",
                            Mileage = 19000m,
                            Model = "Accord",
                            PlateNumber = "OM-30001",
                            VIN = "OMVIN2026000000004",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.AppointmentModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("Appointments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.CustomerProfileModel", "CustomerProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.MechanicProfileModel", "MechanicProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("MechanicProfileId");

                    b.HasOne("VehicleServiceCenter.Models.ServiceTypeModel", "ServiceType")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.VehicleModel", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CustomerProfile");

                    b.Navigation("MechanicProfile");

                    b.Navigation("ServiceType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.CustomerProfileModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.UserModel", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("VehicleServiceCenter.Models.CustomerProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.InvoiceModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.ServiceOrderModel", "ServiceOrder")
                        .WithOne("Invoice")
                        .HasForeignKey("VehicleServiceCenter.Models.InvoiceModel", "ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.MechanicProfileModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("MechanicProfiles")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.UserModel", "User")
                        .WithOne("MechanicProfile")
                        .HasForeignKey("VehicleServiceCenter.Models.MechanicProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.PaymentModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.InvoiceModel", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderItemModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.ServiceOrderModel", "ServiceOrder")
                        .WithMany("ServiceOrderItems")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.ServiceTypeModel", "ServiceType")
                        .WithMany("ServiceOrderItems")
                        .HasForeignKey("ServiceTypeId");

                    b.HasOne("VehicleServiceCenter.Models.SparePartModel", "SparePart")
                        .WithMany("ServiceOrderItems")
                        .HasForeignKey("SparePartId");

                    b.Navigation("ServiceOrder");

                    b.Navigation("ServiceType");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.AppointmentModel", "Appointment")
                        .WithOne("ServiceOrder")
                        .HasForeignKey("VehicleServiceCenter.Models.ServiceOrderModel", "AppointmentId");

                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.CustomerProfileModel", "CustomerProfile")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.MechanicProfileModel", "MechanicProfile")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("MechanicProfileId");

                    b.HasOne("VehicleServiceCenter.Models.VehicleModel", "Vehicle")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Branch");

                    b.Navigation("CustomerProfile");

                    b.Navigation("MechanicProfile");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.SparePartModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("SpareParts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.CustomerProfileModel", "CustomerProfile")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.AppointmentModel", b =>
                {
                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.BranchModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MechanicProfiles");

                    b.Navigation("ServiceOrders");

                    b.Navigation("SpareParts");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.CustomerProfileModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrders");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.InvoiceModel", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.MechanicProfileModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderModel", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("ServiceOrderItems");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceTypeModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrderItems");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.SparePartModel", b =>
                {
                    b.Navigation("ServiceOrderItems");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.UserModel", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("MechanicProfile");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.VehicleModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
