// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleServiceCenter;

#nullable disable

namespace VehicleServiceCenter.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260809184512_FixSeedUserPasswords")]
    partial class FixSeedUserPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleServiceCenter.Models.AppointmentModel", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("MechanicProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("MechanicProfileId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 1,
                            CreatedAt = new DateTime(2026, 8, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 1,
                            MechanicProfileId = 1,
                            Notes = "Regular maintenance and oil change",
                            ServiceTypeId = 1,
                            Status = "Confirmed",
                            VehicleId = 1
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDate = new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 1,
                            CreatedAt = new DateTime(2026, 8, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 2,
                            MechanicProfileId = 1,
                            Notes = "Brake inspection",
                            ServiceTypeId = 2,
                            Status = "Pending",
                            VehicleId = 2
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDate = new DateTime(2026, 8, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 2,
                            CreatedAt = new DateTime(2026, 8, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 3,
                            MechanicProfileId = 2,
                            Notes = "Check engine warning light",
                            ServiceTypeId = 3,
                            Status = "Confirmed",
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.BranchModel", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Address = "Muscat, Oman",
                            BranchName = "Main Branch",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "main@vehicleservice.com",
                            IsActive = true,
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            PhoneNumber = "99995555"
                        },
                        new
                        {
                            BranchId = 2,
                            Address = "Barka, Oman",
                            BranchName = "Barka Branch",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "barka@vehicleservice.com",
                            IsActive = true,
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            PhoneNumber = "26891234"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.CustomerProfileModel", b =>
                {
                    b.Property<int>("CustomerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");

                    b.HasData(
                        new
                        {
                            CustomerProfileId = 1,
                            Address = "Barka, Oman",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2001, 5, 10),
                            UserId = 3
                        },
                        new
                        {
                            CustomerProfileId = 2,
                            Address = "Muscat, Oman",
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 8, 15),
                            UserId = 4
                        },
                        new
                        {
                            CustomerProfileId = 3,
                            Address = "Barka, Oman",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1999, 3, 20),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.InvoiceModel", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ServiceOrderId")
                        .IsUnique();

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            DiscountAmount = 0.000m,
                            DueDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0001",
                            IssueDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Paid in full",
                            ServiceOrderId = 1,
                            Status = "Paid",
                            Subtotal = 33.500m,
                            TaxAmount = 0.000m,
                            TotalAmount = 33.500m
                        },
                        new
                        {
                            InvoiceId = 2,
                            DiscountAmount = 0.000m,
                            DueDate = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0002",
                            IssueDate = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Payment pending",
                            ServiceOrderId = 2,
                            Status = "Unpaid",
                            Subtotal = 65.000m,
                            TaxAmount = 0.000m,
                            TotalAmount = 65.000m
                        },
                        new
                        {
                            InvoiceId = 3,
                            DiscountAmount = 0.000m,
                            DueDate = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-0003",
                            IssueDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Payment pending",
                            ServiceOrderId = 3,
                            Status = "Unpaid",
                            Subtotal = 40.000m,
                            TaxAmount = 0.000m,
                            TotalAmount = 40.000m
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.MechanicProfileModel", b =>
                {
                    b.Property<int>("MechanicProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicProfileId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MechanicProfileId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MechanicProfiles");

                    b.HasData(
                        new
                        {
                            MechanicProfileId = 1,
                            BranchId = 1,
                            ExperienceYears = 7,
                            HireDate = new DateOnly(2022, 1, 10),
                            IsAvailable = true,
                            Specialization = "Engine Repair",
                            UserId = 6
                        },
                        new
                        {
                            MechanicProfileId = 2,
                            BranchId = 2,
                            ExperienceYears = 5,
                            HireDate = new DateOnly(2023, 3, 15),
                            IsAvailable = true,
                            Specialization = "Electrical Systems",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.PaymentModel", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasFilter("[TransactionReference] IS NOT NULL");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 33.500m,
                            InvoiceId = 1,
                            Notes = "Full payment",
                            PaymentDate = new DateTime(2026, 8, 10, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            Status = "Completed",
                            TransactionReference = "TXN-2026-0001"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 30.000m,
                            InvoiceId = 2,
                            Notes = "Partial payment",
                            PaymentDate = new DateTime(2026, 8, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            Status = "Completed",
                            TransactionReference = "TXN-2026-0002"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderItemModel", b =>
                {
                    b.Property<int>("ServiceOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceOrderItemId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("LaborHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SparePartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ServiceOrderItemId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("SparePartId");

                    b.ToTable("ServiceOrderItems");

                    b.HasData(
                        new
                        {
                            ServiceOrderItemId = 1,
                            Description = "Oil change service",
                            ItemType = "Service",
                            LaborHours = 0.75m,
                            Quantity = 1,
                            ServiceOrderId = 1,
                            ServiceTypeId = 1,
                            Subtotal = 25.000m,
                            UnitPrice = 25.000m
                        },
                        new
                        {
                            ServiceOrderItemId = 2,
                            Description = "Oil filter replacement",
                            ItemType = "Part",
                            Quantity = 1,
                            ServiceOrderId = 1,
                            SparePartId = 1,
                            Subtotal = 8.500m,
                            UnitPrice = 8.500m
                        },
                        new
                        {
                            ServiceOrderItemId = 3,
                            Description = "Brake inspection service",
                            ItemType = "Service",
                            LaborHours = 1.00m,
                            Quantity = 1,
                            ServiceOrderId = 2,
                            ServiceTypeId = 2,
                            Subtotal = 30.000m,
                            UnitPrice = 30.000m
                        },
                        new
                        {
                            ServiceOrderItemId = 4,
                            Description = "Front brake pads",
                            ItemType = "Part",
                            Quantity = 1,
                            ServiceOrderId = 2,
                            SparePartId = 2,
                            Subtotal = 35.000m,
                            UnitPrice = 35.000m
                        },
                        new
                        {
                            ServiceOrderItemId = 5,
                            Description = "Engine diagnostic service",
                            ItemType = "Service",
                            LaborHours = 1.00m,
                            Quantity = 1,
                            ServiceOrderId = 3,
                            ServiceTypeId = 3,
                            Subtotal = 40.000m,
                            UnitPrice = 40.000m
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderModel", b =>
                {
                    b.Property<int>("ServiceOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceOrderId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerComplaint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MechanicProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ServiceOrderId");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("MechanicProfileId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceOrders");

                    b.HasData(
                        new
                        {
                            ServiceOrderId = 1,
                            AppointmentId = 1,
                            BranchId = 1,
                            CompletionDate = new DateTime(2026, 8, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Vehicle needs regular maintenance",
                            CustomerProfileId = 1,
                            Diagnosis = "Oil and filter replacement required",
                            MechanicProfileId = 1,
                            OrderDate = new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 33.500m,
                            VehicleId = 1
                        },
                        new
                        {
                            ServiceOrderId = 2,
                            AppointmentId = 2,
                            BranchId = 1,
                            CreatedAt = new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Customer requested brake inspection",
                            CustomerProfileId = 2,
                            Diagnosis = "Brake system inspection in progress",
                            MechanicProfileId = 1,
                            OrderDate = new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "In Progress",
                            TotalAmount = 65.000m,
                            VehicleId = 2
                        },
                        new
                        {
                            ServiceOrderId = 3,
                            AppointmentId = 3,
                            BranchId = 2,
                            CreatedAt = new DateTime(2026, 8, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerComplaint = "Engine warning light is on",
                            CustomerProfileId = 3,
                            Diagnosis = "Diagnostic inspection required",
                            MechanicProfileId = 2,
                            OrderDate = new DateTime(2026, 8, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalAmount = 40.000m,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceTypeModel", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            ServiceTypeId = 1,
                            BasePrice = 25.000m,
                            Description = "Engine oil and oil filter replacement",
                            EstimatedDurationMinutes = 45,
                            IsActive = true,
                            Name = "Oil Change"
                        },
                        new
                        {
                            ServiceTypeId = 2,
                            BasePrice = 30.000m,
                            Description = "Complete brake system inspection",
                            EstimatedDurationMinutes = 60,
                            IsActive = true,
                            Name = "Brake Inspection"
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            BasePrice = 40.000m,
                            Description = "Computerized engine diagnostic service",
                            EstimatedDurationMinutes = 60,
                            IsActive = true,
                            Name = "Engine Diagnostic"
                        },
                        new
                        {
                            ServiceTypeId = 4,
                            BasePrice = 15.000m,
                            Description = "Vehicle battery inspection and replacement",
                            EstimatedDurationMinutes = 30,
                            IsActive = true,
                            Name = "Battery Replacement"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.SparePartModel", b =>
                {
                    b.Property<int>("SparePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SparePartId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SparePartId");

                    b.HasIndex("BranchId");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("SpareParts");

                    b.HasData(
                        new
                        {
                            SparePartId = 1,
                            BranchId = 1,
                            Description = "Standard engine oil filter",
                            IsAvailable = true,
                            PartName = "Oil Filter",
                            PartNumber = "OF-001",
                            ReorderLevel = 10,
                            StockQuantity = 50,
                            UnitPrice = 8.500m
                        },
                        new
                        {
                            SparePartId = 2,
                            BranchId = 1,
                            Description = "Front brake pads",
                            IsAvailable = true,
                            PartName = "Brake Pads",
                            PartNumber = "BP-001",
                            ReorderLevel = 5,
                            StockQuantity = 20,
                            UnitPrice = 35.000m
                        },
                        new
                        {
                            SparePartId = 3,
                            BranchId = 2,
                            Description = "12V vehicle battery",
                            IsAvailable = true,
                            PartName = "Car Battery",
                            PartNumber = "BAT-001",
                            ReorderLevel = 3,
                            StockQuantity = 15,
                            UnitPrice = 45.000m
                        },
                        new
                        {
                            SparePartId = 4,
                            BranchId = 2,
                            Description = "Engine air filter",
                            IsAvailable = true,
                            PartName = "Air Filter",
                            PartNumber = "AF-001",
                            ReorderLevel = 5,
                            StockQuantity = 30,
                            UnitPrice = 12.000m
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 122222,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hawa@example.com",
                            IsActive = true,
                            Password = "$2a$11$ddvzOew6X6eRPWFL05eUHepg3eEwIUcR3PRS0QE64qxIgGaecTkZS",
                            PhoneNumber = "99990000",
                            Role = "Admin",
                            UserName = "Hawa"
                        },
                        new
                        {
                            UserId = 23333,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohammed@example.com",
                            IsActive = true,
                            Password = "$2a$11$njiRWwm346PHbIdUUNQ9q.zTnQ60S7s81iFMnb.i0oY/MUWj2UOCe",
                            PhoneNumber = "99999900",
                            Role = "Admin",
                            UserName = "Mohammed"
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.VehicleModel", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Mileage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VIN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.HasIndex("VIN")
                        .IsUnique()
                        .HasFilter("[VIN] IS NOT NULL");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Color = "White",
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 1,
                            Make = "Toyota",
                            Mileage = 45000m,
                            Model = "Camry",
                            PlateNumber = "12345",
                            VIN = "OMVIN000000000001",
                            Year = 2022
                        },
                        new
                        {
                            VehicleId = 2,
                            Color = "Black",
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 2,
                            Make = "Nissan",
                            Mileage = 62000m,
                            Model = "Altima",
                            PlateNumber = "23456",
                            VIN = "OMVIN000000000002",
                            Year = 2021
                        },
                        new
                        {
                            VehicleId = 3,
                            Color = "Silver",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerProfileId = 3,
                            Make = "Honda",
                            Mileage = 28000m,
                            Model = "Accord",
                            PlateNumber = "34567",
                            VIN = "OMVIN000000000003",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.AppointmentModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("Appointments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.CustomerProfileModel", "CustomerProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.MechanicProfileModel", "MechanicProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("MechanicProfileId");

                    b.HasOne("VehicleServiceCenter.Models.ServiceTypeModel", "ServiceType")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.VehicleModel", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CustomerProfile");

                    b.Navigation("MechanicProfile");

                    b.Navigation("ServiceType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.CustomerProfileModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.UserModel", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("VehicleServiceCenter.Models.CustomerProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.InvoiceModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.ServiceOrderModel", "ServiceOrder")
                        .WithOne("Invoice")
                        .HasForeignKey("VehicleServiceCenter.Models.InvoiceModel", "ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.MechanicProfileModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("MechanicProfiles")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.UserModel", "User")
                        .WithOne("MechanicProfile")
                        .HasForeignKey("VehicleServiceCenter.Models.MechanicProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.PaymentModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.InvoiceModel", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderItemModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.ServiceOrderModel", "ServiceOrder")
                        .WithMany("ServiceOrderItems")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.ServiceTypeModel", "ServiceType")
                        .WithMany("ServiceOrderItems")
                        .HasForeignKey("ServiceTypeId");

                    b.HasOne("VehicleServiceCenter.Models.SparePartModel", "SparePart")
                        .WithMany("ServiceOrderItems")
                        .HasForeignKey("SparePartId");

                    b.Navigation("ServiceOrder");

                    b.Navigation("ServiceType");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.AppointmentModel", "Appointment")
                        .WithOne("ServiceOrder")
                        .HasForeignKey("VehicleServiceCenter.Models.ServiceOrderModel", "AppointmentId");

                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.CustomerProfileModel", "CustomerProfile")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceCenter.Models.MechanicProfileModel", "MechanicProfile")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("MechanicProfileId");

                    b.HasOne("VehicleServiceCenter.Models.VehicleModel", "Vehicle")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Branch");

                    b.Navigation("CustomerProfile");

                    b.Navigation("MechanicProfile");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.SparePartModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.BranchModel", "Branch")
                        .WithMany("SpareParts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleServiceCenter.Models.CustomerProfileModel", "CustomerProfile")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.AppointmentModel", b =>
                {
                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.BranchModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MechanicProfiles");

                    b.Navigation("ServiceOrders");

                    b.Navigation("SpareParts");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.CustomerProfileModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrders");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.InvoiceModel", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.MechanicProfileModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceOrderModel", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("ServiceOrderItems");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.ServiceTypeModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrderItems");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.SparePartModel", b =>
                {
                    b.Navigation("ServiceOrderItems");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.UserModel", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("MechanicProfile");
                });

            modelBuilder.Entity("VehicleServiceCenter.Models.VehicleModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
